name: Build for Linux

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build (branch, tag or SHA)'
        required: false
        default: 'main'

jobs:
  build:
    name: Build ShapeScript for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Build it
        run: |
          swift build --configuration release --static-swift-stdlib
          SWIFTFORMAT_BIN_PATH=`swift build --configuration release --show-bin-path`
          mkdir -p "${HOME}/release"
          cp $SWIFTFORMAT_BIN_PATH/shapescript "${HOME}/release/shapescript"
          chmod +x "${HOME}/release/shapescript"
          cd "${HOME}/release"
          zip -j "ShapeScriptCLI-linux-x86_64.zip" shapescript
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v7
        with:
          name: ShapeScriptCLI-linux-x86_64
          path: ~/release/ShapeScriptCLI-linux-x86_64.zip
          retention-days: 5
